### PR TITLE
refactor to splat

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
[Splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6) is a very PowerShell-y concept. The idea is that you define the parameters for your command in a hashtable and then use the `@` sign instead of the `$` to "splat" them onto a command.

This change refactors to that so we don't have to use `Add-Member`.

### CODE REVIEW

**Comment by shanselman** [comment]
Sorry I was messing around. Would you rebase on top of the new stuff?

**Comment by TylerLeonhardt** [comment]
Done!

**Comment by gpduck** [comment]
Another problem with the existing if statements is they won't for values that cast to $false (like empty string, $null, and 0):

```
if(!$terminalProfile.backgroundImage){
    $terminalProfile | Add-Member -NotePropertyName backgroundImage -NotePropertyValue ""
}
```

If backgroundImage is present but set to "", PowerShell will cast the "" to $false and then try to add the member on top of the existing member, generating an error.  A safe way to implement the same logic would be to use Get-Member to test for the property existance:

```
if(!(Get-Member -Name backgroundImage -InputObject $TerminalProfile)) {
    $terminalProfile | Add-Member -NotePropertyName backgroundImage -NotePropertyValue ""
}
```

But switching to use the parameters on Set-MSTerminalProfile is a better solution :)

**Comment by shanselman** [comment]
So sorry about this, but you still stomped on the Seconds parameter and set it back to a hard coded 5?

**Comment by TylerLeonhardt** [comment]
Ah. No worries. I'll fix 👍

**Comment by TylerLeonhardt** [comment]
Ok there we go! I even moved over the Mood script - only 28 lines (most of which are parameter handling & whitespace) not bad!

**Comment by shanselman** [comment]
So clean @TylerLeonhardt! :shipit:

**Pull request merged**
